// Updated site data with all real links
window.SITE_DATA = {
  name: "Guilherme Junqueira",
  role: "Finance Ph.D. Candidate",
  affiliation: "University of Florida · Warrington College of Business",
  ufPage: "https://warrington.ufl.edu/directory/guilherme-junqueira/",
  email: "gjunqueira@ufl.edu",
  cvUrl: "https://www.dropbox.com/scl/fi/8hy57owk2mf6vcoat2vk1/CV_Junqueira_Guilherme.pdf?rlkey=w43lvnootw9a7yeo1e0njb65o&st=yfmffcxb&raw=1",
  twitter: "https://x.com/_GJunqueira",
  twitterHandle: "_GJunqueira",
  linkedin: "https://www.linkedin.com/in/guilhermejunqueira/",
  scholar: "#",
  office: "Stuzin Hall, Office 311",
  officeAddress: "1454 Union Rd, Gainesville, FL 32611",
  visiting: [
    { label: "Visiting Ph.D. Student, Fall 2026", at: "Tuck School of Business, Dartmouth", url: "https://tuck.dartmouth.edu/" },
    { label: "Visiting Researcher", at: "Insper", url: "https://www.insper.edu.br/en/home" },
  ],
  fields: ["Private Capital", "Entrepreneurship & Innovation", "Development & Finance", "Labor & Finance"],
  bio:
    "I study how the design of tax incentives, cash transfer programs, and housing policy shapes who starts, finances, and grows new firms — with implications for private capital, innovation, and economic mobility. My work combines administrative and proprietary micro-data with quasi-experimental methods to speak to questions in entrepreneurship, development, and corporate finance.",
  longBio:
    "I am a fourth-year finance Ph.D. candidate at the University of Florida's Warrington College of Business. I will be a Visiting Ph.D. Student at Dartmouth's Tuck School of Business in Fall 2026, and I am a Visiting Researcher at Insper. My research sits at the intersection of private capital, entrepreneurship, and public policy. I use administrative and proprietary micro-data — together with quasi-experimental designs — to study how the design of tax incentives, transfer programs, and housing policy shapes who starts, finances, and grows new firms, and what that means for innovation and economic mobility.",
  publications: [
    {
      n: 1,
      title: "Democratizing Venture Capital: Tax Incentives and the Geographic Expansion of Startup Investing",
      url: "#",
      coauthors: [{ name: "Murillo Campello", url: "https://murillocampello.com/" }],
      venue: "NBER Tax Policy and the Economy, Volume 41",
      status: "forthcoming",
      topConferences: [
        { name: "NBER Tax Policy and the Economy Conference, 2026", url: "https://www.nber.org/conferences/41st-annual-nber-tax-policy-and-economy-conference-2026" },
      ],
      conferences: [
        { name: "NBER Tax Policy and the Economy Conference, 2026", url: "https://www.nber.org/conferences/41st-annual-nber-tax-policy-and-economy-conference-2026" },
      ],
    },
  ],
  workingPapers: [
    {
      n: 2,
      title: "Tax Incentives and Venture Capital Risk-Taking: Evidence from the QSBS Program",
      url: "https://conference.nber.org/conf_papers/f233872.pdf",
      versions: [
        { name: "Working Paper", url: "https://conference.nber.org/conf_papers/f233872.pdf" },
        { name: "Oxford CBT WP", url: "https://oxfordtax.sbs.ox.ac.uk/sitefiles/wp25.10-guilherme-junqueira.pdf" },
      ],
      bibtex: `@unpublished{campello2026taxincentives,
  author = {Campello, Murillo and Junqueira, Guilherme},
  title  = {Tax Incentives and Venture Capital Risk-Taking: Evidence from the QSBS Program},
  year   = {2026},
  note   = {Working Paper}
}`,
      apa: "Campello, M., & Junqueira, G. (2026). Tax incentives and venture capital risk-taking: Evidence from the QSBS program. Working Paper.",
      coauthors: [{ name: "Murillo Campello", url: "https://murillocampello.com/" }],
      abstract:
        "Do tax subsidies prompt investors to take on risk? We address this question looking at investors' responses to changes to the Qualified Small Business Stock (QSBS) program, which cut capital gains taxes on startup investing. We do so under a framework in which some startup investors—venture capitalists (VCs)—combine outside funding with incentive-based compensation, while others invest their own funds. Using bunching, regression discontinuity, triple-differences, and matching designs that exploit industry eligibility, investment vintage, and holding-period requirements, we analyze data from 158 thousand investor–firm pairings over two decades. We first identify strategic investment timing, with subsidies prompting clustering at tax-eligible holding-period thresholds. We then document strategic capital allocation, with firms just below eligibility thresholds receiving more funding than those just above. Most notably, when and where tax subsidies apply, VCs shift their project selection toward riskier ventures: they invest more in pre-commercial stage startups, become more likely to provide startups with their initial capital, and invest more in startups with pre-existing debt, while becoming less likely to co-syndicate their investments. Tax-subsidized VC-backed ventures show higher failure rates. On the flip side, they attain higher valuations at exit and are more likely to reach \"unicorn status.\" None of these patterns are observed for comparable non-VC investors receiving the same tax subsidies. Our tests also suggest that tax incentives lead to reallocation toward more innovative industries, yielding more impactful patents. Our study is the first to show that tax policy can shift entrepreneurial financing toward riskier, more innovative, valuable ventures.",
      awards: ["Best Paper of the Conference, Spanish Finance Association's 32nd Finance Forum"],
      coverage: [
        { name: "ECGI Blog", url: "https://www.ecgi.global/publications/blog/tax-incentives-and-the-venture-capital-appetite-for-risk" },
      ],
      topConferences: [
        { name: "SFS Cavalcade 2026", url: "https://www.conftool.com/sfs-cavalcade-2026/sessions.php" },
        { name: "FIRS 2026", url: "https://www.conftool.org/firs2026/sessions.php" },
        { name: "EFA 2026", url: "https://www.conftool.com/efa2026/sessions.php" },
        { name: "NBER New Dev. in Long-Term Asset Management Spring 2026", url: "https://www.nber.org/conferences/new-developments-long-term-asset-management-spring-2026", recordingUrl: "https://www.youtube.com/watch?v=__BDxxwHTlk" },
        { name: "NBER Place-Based Policies & Entrepreneurship Fall 2025*", url: "https://www.nber.org/conferences/place-based-policies-and-entrepreneurship-fall-2025" },
        { name: "NBER Public Economics Fall 2025*", url: "https://www.nber.org/conferences/public-economics-program-meeting-fall-2025" },
        { name: "NBER Econ. Analysis of Business Taxation Spring 2025*", url: "https://www.nber.org/conferences/economic-analysis-business-taxation-spring-2025" },
        { name: "ECGI Public Lecture*", url: "https://www.ecgi.global/publications/videos/tax-incentives-and-venture-capital-risk-taking-murillo-campello", recordingUrl: "https://www.ecgi.global/publications/videos/tax-incentives-and-venture-capital-risk-taking-murillo-campello" },
      ],
      conferences: [
        { name: "SFS Cavalcade 2026", url: "https://www.conftool.com/sfs-cavalcade-2026/sessions.php" },
        { name: "FIRS 2026", url: "https://www.conftool.org/firs2026/sessions.php" },
        { name: "EFA 2026", url: "https://www.conftool.com/efa2026/sessions.php" },
        { name: "NBER New Dev. in Long-Term Asset Management Spring 2026", url: "https://www.nber.org/conferences/new-developments-long-term-asset-management-spring-2026", recordingUrl: "https://www.youtube.com/watch?v=__BDxxwHTlk" },
        { name: "NBER Place-Based Policies & Entrepreneurship Fall 2025*", url: "https://www.nber.org/conferences/place-based-policies-and-entrepreneurship-fall-2025" },
        { name: "NBER Public Economics Fall 2025*", url: "https://www.nber.org/conferences/public-economics-program-meeting-fall-2025" },
        { name: "NBER Econ. Analysis of Business Taxation Spring 2025*", url: "https://www.nber.org/conferences/economic-analysis-business-taxation-spring-2025" },
        { name: "University of Melbourne's Finance Down Under Conference 2026", url: "https://fbe.unimelb.edu.au/conferences/fdu" },
        { name: "LSE Workshop on Capital Gains Tax 2026", url: "https://www.lse.ac.uk/international-inequalities/research/wealth-elites-and-tax-justice/centax" },
        { name: "SGF Conference at the University of Zurich 2026", url: "https://www.df.uzh.ch/en/news-events/events/2026/2026-SGF-conference.html" },
        { name: "CESifo Area Conference on Public Economics 2026", url: "https://www.ifo.de/en/cesifo/event/2026-04-15/cesifo-area-conference-public-economics-2026" },
        { name: "London Business School's Private Capital Symposium 2025", url: "https://drive.google.com/file/d/1-sO1gMD8QtmN0qakvzS66MGGKq0BkfJH/view" },
        { name: "University of Oregon Finance Conference 2025", url: "https://business.uoregon.edu/faculty/departments/finance/conference" },
        { name: "University of Oxford Private Equity Research Consortium Symposium 2025*", url: "https://uncipc.org/wp-content/uploads/2025/06/PERC-Oxford-2025_Materials2.pdf" },
        { name: "University of Oxford Centre for Business Taxation Doctoral Conference 2025", url: "https://oxfordtax.web.ox.ac.uk/sitefiles/doctoral-conference-2025-programme.pdf" },
        { name: "Finance Theory Group Summer School Conference 2025", url: "https://foster.uw.edu/wp-content/uploads/2025/06/evening_schedule.pdf" },
        { name: "Latin American Economic Association (LACEA) Conference 2025", url: "https://www.lacea2025.org/en" },
        { name: "Boca Finance and Real Estate Conference 2025", url: "https://business.fau.edu/boca-finance-and-real-estate-conference/" },
        { name: "RCF-ECGI Corporate Finance & Governance Conference 2025", url: "https://www.ecgi.global/system/files/2025-09/rcf-ecgi-2025-day-1-track-a-programme.pdf" },
        { name: "Spanish Finance Association's 32nd Finance Forum 2025", url: "https://finance-forum.es/" },
      ],
      seminars: [
        { name: "Bank of England*", year: 2025 },
        { name: "CUNEF Universidad*", year: 2025 },
        { name: "ECGI Public Lecture*", year: 2025 },
        { name: "Insper Instituto de Ensino e Pesquisa", year: 2025 },
        { name: "University of Alabama*", year: 2025 },
        { name: "University of Cambridge*", year: 2025 },
        { name: "University of Milan*", year: 2025 },
        { name: "University of Naples Federico II*", year: 2025 },
        { name: "University of São Paulo", year: 2025 },
        { name: "UT San Antonio", year: 2025 },
        { name: "National University of Singapore", year: 2026 },
        { name: "Rutgers University*", year: 2026 },
        { name: "Tulane University*", year: 2026 },
        { name: "University of Edinburgh*", year: 2026 },
        { name: "University of Glasgow*", year: 2026 },
        { name: "University of Miami*", year: 2026 },
        { name: "University of Tennessee*", year: 2026 },
      ],
    },
    {
      n: 3,
      title: "Entrepreneurship on a Safety Net: Evidence from the World's Largest Cash Transfer Program",
      url: "https://westernfinance-portal.org/viewpaper?n=1044036",
      versions: [
        { name: "Working Paper", url: "https://westernfinance-portal.org/viewpaper?n=1044036" },
      ],
      bibtex: `@unpublished{campello2026entrepreneurship,
  author = {Campello, Murillo and Junqueira, Guilherme and Lagaras, Spyridon},
  title  = {Entrepreneurship on a Safety Net: Evidence from the World's Largest Cash Transfer Program},
  year   = {2026},
  note   = {Working Paper}
}`,
      apa: "Campello, M., Junqueira, G., & Lagaras, S. (2026). Entrepreneurship on a safety net: Evidence from the world's largest cash transfer program. Working Paper.",
      coauthors: [
        { name: "Murillo Campello", url: "https://murillocampello.com/" },
        { name: "Spyridon Lagaras", url: "https://sites.google.com/view/spyridonlagaras/home" },
      ],
      abstract:
        "Do social transfer programs boost entrepreneurship among low-income populations? We address this question by examining Brazil's Bolsa Família—the world's largest cash transfer program—and its effects on entrepreneurial entry, performance, and economic mobility. Using administrative data covering 2.3 million sole-proprietorships, we track entrepreneurs through the complete business lifecycle—from entry through performance to post-failure employment. We address selection combining instrumental variables—exploiting bunching across program eligibility thresholds—with matching and granular fixed effects. We first show that cash transfers increase transitions into entrepreneurship from both non-employment and wage employment, increasing beneficiaries' representation among entrepreneurs. We then identify systematic performance disadvantages: cash-transfer entrepreneurs exhibit lower survival, business growth, employment creation, and credit access, eventually facing higher rates of tax violations and debt collection proceedings. Performance gaps appear to reflect two mechanisms: managerial constraints—evident in hiring less-educated workers at higher wages with stable employment—and program dependence, revealed by income bunching at eligibility thresholds and widening gaps among longer-tenured beneficiaries. Yet these same hiring patterns, along with stronger recruitment of racial minorities, produce positive spillovers extending beyond cash-transfer recipients. Examining post-entrepreneurship trajectories, we find that cash-transfer entrepreneurs transition back to employment faster and their wage losses are 61% smaller than those of other failed entrepreneurs. Overall, our analysis reveals that cash-transfer businesses remain trapped in subsistence, generating neither growth nor economic transformation, but the entrepreneurial experience itself builds human capital that disproportionately benefits beneficiaries.",
      topConferences: [
        { name: "WFA 2026", url: "https://westernfinance-portal.org/conference" },
        { name: "EFA 2026", url: "https://www.conftool.com/efa2026/sessions.php" },
        { name: "CEPR Development Economics Symposium 2026", url: "https://cepr.org/events/event-series/development-economics-symposium/cepr-development-economics-joint-tcd-2026-1" },
        { name: "CEPR Summer Conference on Financial Intermediation and Corporate Finance 2026*", url: "https://cepr.org/events/8th-summer-conference-financial-intermediation-and-corporate-finance" },
        { name: "ABFER Annual Conference 2026", url: "https://abfer.org/events/abfer-events/annual-conference/417:accfp2026" },
        { name: "Society of Labor Economists (SOLE) Annual Meeting 2026", url: "https://www.sole-jole.org/index.php?option=com_content&view=article&id=147:sole-2026-submissions-now-open&catid=23:latest-news" },
        { name: "HEC Paris Entrepreneurship Workshop 2025", url: "https://hecparisentrepreneurship.github.io/" },
      ],
      conferences: [
        { name: "WFA 2026", url: "https://westernfinance-portal.org/conference" },
        { name: "EFA 2026", url: "https://www.conftool.com/efa2026/sessions.php" },
        { name: "CEPR Development Economics Symposium 2026", url: "https://cepr.org/events/event-series/development-economics-symposium/cepr-development-economics-joint-tcd-2026-1" },
        { name: "CEPR Summer Conference on Financial Intermediation and Corporate Finance 2026*", url: "https://cepr.org/events/8th-summer-conference-financial-intermediation-and-corporate-finance" },
        { name: "ABFER Annual Conference 2026", url: "https://abfer.org/events/abfer-events/annual-conference/417:accfp2026" },
        { name: "Society of Labor Economists (SOLE) Annual Meeting 2026", url: "https://www.sole-jole.org/index.php?option=com_content&view=article&id=147:sole-2026-submissions-now-open&catid=23:latest-news" },
        { name: "Inaugural Rutgers Finance Research Conference 2026*", url: "https://www.ssrn.com/index.cfm/en/janda/announcement/?id=18444" },
        { name: "Luso-Brazilian Finance Network (Lubrafin) Meeting 2026", url: "https://sites.google.com/view/lubrafin/home" },
        { name: "University of Minnesota Data-Intensive Research Conference 2026", url: "https://lcc.umn.edu/DIRC" },
        { name: "Lake District Workshop in Corporate Finance 2026*", url: "https://wp.lancs.ac.uk/ldwcf/" },
        { name: "IFN Stockholm Conference on Firms and Human Capital 2026*", url: "https://www.ifn.se/en/seminars-and-calendar/ifn-stockholm-conference/2026-firm-competitiveness/" },
        { name: "CCA-ESCP Workshop on Fin. Institutions & Corporate Finance 2026*", url: "https://escp.eu/events/ccaescpworkshop" },
        { name: "HEC Paris Entrepreneurship Workshop 2025", url: "https://hecparisentrepreneurship.github.io/" },
        { name: "WEFI Student-Led Workshop 2025", url: "https://workshop-efi.com/student-led-workshop/" },
      ],
      seminars: [
        { name: "Brazilian Finance Society", year: 2025 },
        { name: "Copenhagen Business School*", year: 2025 },
        { name: "Insper Instituto de Ensino e Pesquisa", year: 2025 },
        { name: "University College Dublin", year: 2026 },
        { name: "University of Florida (Economics Dept.)", year: 2026 },
        { name: "Washington University in St. Louis*", year: 2026 },
      ],
    },
    {
      n: 4,
      title: "Homeownership Hinders Entrepreneurship: Evidence from a Housing Lottery",
      url: "#",
      coauthors: [
        { name: "Murillo Campello", url: "https://murillocampello.com/" },
        { name: "Changcheng Song", url: "https://sites.google.com/site/songchch02/" },
      ],
      topConferences: [
        { name: "World Bank Land and Property Research Conference 2026*", url: "https://www.worldbank.org/en/events/2026/04/29/land-and-property-research-conference" },
      ],
      conferences: [
        { name: "World Bank Land and Property Research Conference 2026*", url: "https://www.worldbank.org/en/events/2026/04/29/land-and-property-research-conference" },
      ],
    },
  ],
  worksInProgress: [
    {
      n: 5,
      title: "Measuring Innovation in U.S. Food Markets",
      coauthors: [],

      topConferences: [
        { name: "NBER Innovation Information Initiative 2025", url: "https://www.nber.org/conferences/innovation-information-initiative-technical-working-group-meeting-fall-2025", recordingUrl: "https://www.youtube.com/watch?v=5ji3nPiLcx8" },
      ],
    },
    {
      n: 6,
      title: "The Industrial Organization of Private Equity",
      coauthors: [
        { name: "Murillo Campello", url: "https://murillocampello.com/" },
        { name: "Michael S. Weisbach", url: "https://u.osu.edu/weisbach.2/" },
      ],
      note: "Granted access to MSCI–Burgiss data by the Private Equity Research Consortium.",
    },
    {
      n: 7,
      title: "The Anatomy of Creative Destruction",
      coauthors: [],
    },
  ],
  teaching: [
    { course: "Financial Management (FIN 4414)",
      level: "Undergraduate, U. Florida",
      role: "Instructor of Record",
      desc: "Corporate capital-raising across the financing lifecycle — venture capital, IPOs, SEOs, bank lending, bond issuances, and project finance & leasing — taught through lectures and Harvard cases (e.g., Pear VC, Netflix, Goodyear, Alibaba).",
      offerings: [
        { term: "Summer 2026", note: "Upcoming" },
        { term: "Summer 2025", note: "Overall rating: 5.00 / 5.00",
          noteRef: "Finance Dept. mean: 3.66/5.00 · College mean: 4.10/5.00",
          syllabus: "https://asset.warrington.ufl.edu/syllabi/20255_FIN4414_Financial%20Management_0774_Junqueira,G.pdf" },
      ],
    },
  ],
  awards: [
    { date: "Mar 2026", text: "Certificate of Outstanding Merit, University of Florida." },
    { date: "Mar 2026", text: "Warrington College's Nomination for University-Level Int'l Student Achievement Award." },
    { date: "Jan 2026", text: "Selected for the IFP PhD Course on Economics of Ideas, Science, and Innovation (Feb–Apr 2026).", url: "https://ifp.org/economics-of-ideas/" },
    { date: "Jul 2025", text: "Best Paper of the Conference, Spanish Finance Association's 32nd Finance Forum.", url: "https://aefin.es/conference-awards/" },
    { date: "May 2025", text: "Taught Financial Management for UF's undergraduate program (overall rating: 5.00/5.00)." },
    { date: "Apr 2025", text: "Selected for the Finance Theory Group Summer School 2025 (Jun 25–28).", url: "https://foster.uw.edu/faculty-research/academic-departments/finance-and-business-economics/financial-theory-group-summer-school-2025/" },
    { date: "Nov 2024", text: "Selected as a 2025 Graduate Fellow in the NBER Innovation Information Initiative (I3).", url: "https://www.nber.org/programs-projects/projects-and-centers/innovative-information-initiative" },
    { date: "Apr 2024", text: "Selected for the Finance & Product Markets Summer School 2024 (Aug 12–16).", url: "https://www.usi.ch/en/feeds/29040" },
    { date: "Mar 2024", text: "Selected for the NBER Entrepreneurship Boot Camp 2024 (Jul 15–19).", url: "https://www.nber.org/conferences/entrepreneurship-research-boot-camp-summer-2024" },
  ],
  // Upcoming/scheduled talks (a curated list for the home page)
  upcomingTalks: [
    { date: "2026", text: "NBER Tax Policy and the Economy Conference", url: "https://www.nber.org/conferences/41st-annual-nber-tax-policy-and-economy-conference-2026" },
    { date: "2026", text: "SFS Cavalcade", url: "https://www.conftool.com/sfs-cavalcade-2026/sessions.php" },
    { date: "2026", text: "WFA Annual Meeting", url: "https://westernfinance-portal.org/conference" },
    { date: "2026", text: "EFA Annual Meeting", url: "https://www.conftool.com/efa2026/sessions.php" },
    { date: "2026", text: "ABFER Annual Conference", url: "https://abfer.org/events/abfer-events/annual-conference/417:accfp2026" },
  ],
  // Discussions and session chair roles
  discussions: [
    {
      paper: "Is C-SALT Harmful to Economic Health?",
      author: "James Hines",
      venue: "CESifo Area Conference on Public Economics",
      year: 2026,
      slidesUrl: "https://www.dropbox.com/scl/fi/qfxopjq5lrdpf3ko9qilz/Discussion_Hines_2026_CESifo_Conference.pdf?rlkey=hnv554grxs2eerxaidfc05760&raw=1",
    },
    {
      paper: "Navigating Crowdfunding Security-Type Choices and Their Long-Term Implications",
      author: "Robert Reardon",
      venue: "RCF–ECGI Corporate Finance and Governance Conference",
      year: 2025,
      slidesUrl: "https://www.dropbox.com/scl/fi/s6b5hupbv73dszujo9b7a/Discussion_Reardon_ECGI_Stevens_2025.pdf?rlkey=bey3ss5grw47rly1z5bineyu0&raw=1",
    },
    {
      paper: "The Uneven Effects of SEC's Accredited Investor Reform",
      author: "Alina Munteanu",
      venue: "Boca Finance and Real Estate Conference",
      year: 2025,
      slidesUrl: "https://www.dropbox.com/scl/fi/nrw8c9hzr4p2qqjuuer3m/Discussion_Munteanu_Boca_2025.pdf?rlkey=tiyh9mo0y8qpwuxi7rd9ras0n&raw=1",
    },
    {
      paper: "Financial Distress Likelihood of European SMEs in Times of Economic Policy Uncertainty",
      author: "F. Hawachi and I. Requeijo",
      venue: "Spanish Finance Association's 32nd Finance Forum",
      year: 2025,
      slidesUrl: "https://www.dropbox.com/scl/fi/dv5pq4f9w4o7ogajsxfdv/Discussion_Hawach_Requeijo_32_Fin_Forum.pdf?rlkey=gpr4ph8ruqxhtf5llcjl2vccz&raw=1",
    },
  ],
  sessionChair: [
    { role: "Session Chair, Corporate Tax Track", venue: "CESifo Area Conference on Public Economics", year: 2026, location: "Munich, Germany" },
  ],
  // Featured talk videos
  videos: [
    { title: "NBER New Dev. in Long-Term Asset Management", year: 2026, url: "https://www.youtube.com/watch?v=__BDxxwHTlk", paper: "Tax Incentives and Venture Capital Risk-Taking" },
    { title: "NBER Innovation Information Initiative", year: 2025, url: "https://www.youtube.com/watch?v=5ji3nPiLcx8", paper: "Measuring Innovation in U.S. Food Markets" },
  ],
  gallery: [
    // Row 1 — anchor moments
    { src: "site/assets/gallery-1.jpeg", caption: "Best Paper Award, Spanish Finance Association", year: 2025 },
    { src: "site/assets/gallery-lbs-2025.jpg?v=3", caption: "Presenting at the London Business School's Private Capital Symposium", year: 2025, pos: "50% 70%" },
    { src: "site/assets/gallery-cambridge-2025.jpg", caption: "High Table dinner at Pembroke College, University of Cambridge, with advisor Murillo Campello", year: 2025 },
    // Row 2 — presentations and ceremony
    { src: "site/assets/gallery-finance-forum-2025.jpg", caption: "Presenting at the Spanish Finance Association's 32nd Finance Forum", year: 2025 },
    { src: "site/assets/gallery-ucd-2026.jpg", caption: "Presenting at the Finance Seminar Series of University College Dublin", year: 2026 },
    { src: "site/assets/gallery-cert-uf-2026.jpg", caption: "Receiving a Certificate of Outstanding Merit, University of Florida", year: 2026 },
    // Row 3 — group photos
    { src: "site/assets/gallery-oxford-cbt-2025.jpg", caption: "Oxford University CBT Doctoral Conference", year: 2025 },
    { src: "site/assets/gallery-nber-bootcamp-2024.jpg", caption: "NBER Entrepreneurship Boot Camp", year: 2024 },
    { src: "site/assets/gallery-lugano-2024.jpg", caption: "Finance & Product Markets Summer School", year: 2024 },
  ],
};
